version: "2"

services:
  tourists-data:
    container_name: tourists-data
    build:
      context: ./data
      dockerfile: ./.docker/tourists-data.dockerfile
    ports:
      - "27017:27017"
  tourists-web-api:
    container_name: tourists-web-api
    build:
      context: ./web-api/
      dockerfile: ./.docker/tourists-web-api.dockerfile
    ports:
      - "8081:80"
    links:
      - "tourists-data"
    # If want to use the host source code and not the contaner one, uncomment this.  [Good for development]
    # volumes:
    #   - ./web-api/:/var/www/tourists-web-api
    working_dir: /var/www/tourists-web-api
  tourists-web-app:
    container_name: tourists-web-app
    build:
      context: ./web-app/
      dockerfile: ./.docker/tourists-web-app.dockerfile
    ports:
      - "80:80"
      - "443:443"
    links:
      - "tourists-web-api"
    volumes:
      - ./web-app/distribution:/usr/share/nginx/html
# networks:
#   tourists:
#     driver: bridge