version: "2"

services:
  tourists-data:
    container_name: tourists-data
    build:
      context: ./data
      dockerfile: ./.docker/tourists-data.dockerfile
    ports:
      - "27017:27017"
  tourists-web-api:
    container_name: tourists-web-api
    build:
      context: ./web-api/
      dockerfile: ./.docker/tourists-web-api.dockerfile
    ports:
      - "8081:8081"
    volumes:
      - ./web-api/:/var/www/tourists-web-api
    working_dir: /var/www/tourists-web-api
  tourists-web-app:
    container_name: tourists-web-app
    build:
      context: ./web-app/
      dockerfile: ./.docker/tourists-web-app.dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./web-app/distribution:/usr/share/nginx/html
    working_dir: /usr/share/nginx/html
    #entrypoint: npm run startDev
# networks:
#   tourists:
#     driver: bridge